# Generated by Django 5.2.4 on 2026-06-19 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdukasiVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id_youtube', models.CharField(max_length=50)),
                ('judul', models.CharField(max_length=150)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('no_telepon', models.CharField(blank=True, default='-', max_length=20)),
                ('alamat', models.TextField(blank=True, default='-')),
                ('total_poin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_reward', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('poin_dibutuhkan', models.IntegerField()),
                ('logo_resource_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatSampah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sampah', models.CharField(max_length=50)),
                ('berat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('poin_didapat', models.IntegerField()),
                ('tanggal_lokasi', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pengguna')),
            ],
        ),
    ]
